name: 'Deployment ğŸš€'
description: 'Deploying my personal blog with nextjs and github pages ğŸ™ğŸ™'
author: 'raveenita'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'The github token secret'

 