# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy my blog on GitHub Pages 

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Installing my packages âš™ï¸
        run: npm ci

      - name: Build my App âš’ï¸
        run: npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploying ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          branch: public # The branch the action should deploy to.
          folder: out # The folder the action should deploy.